server {
    listen 80;
    server_name _;

    # Raíz donde están los archivos estáticos
    root /usr/share/nginx/html;
    index index.html;

    # Soporte para React Router (Single Page Application)
    # Redirige cualquier ruta no encontrada a index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy para las peticiones a la API
    location /api/ {
        # 'lumins-api' es el nombre del servicio del backend en docker-compose
        proxy_pass http://lumins-api:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Proxy para Socket.io (WebSockets)
    location /socket.io/ {
        proxy_pass http://lumins-api:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
